movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movi_id>/',views.details,name='details'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from . forms import movieform
# Create your views here.

def index(request,):
    movi=movie.objects.all()
    context={
        'movielist':movi

    }
    return render(request,"index.html",context)

def details(request,movi_id):
    movi=movie.objects.get(id=movi_id)
    return render(request,'details.html',{'movie':movi})

def addmovie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        move=movie(name=name,desc=desc,year=year,img=img)
        move.save()
    return render(request,'add.html')

def update(request,id):
    mov=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':mov})

def delete(request,id):
    if request.method=='POST':
        movi=movie.objects.get(id=id)
        movi.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter movie name"><br>
  <input type="text" name="desc" placeholder="Enter Description"><br>
  <input type="text" name="year" placeholder="Enter movie Year"><br>
  <input type="file" name="img" ><br>
  <input type="submit">

</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    Online Movies
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">\
{% csrf_token %}

    ARE YOU WNT TO DELETE THIS MOVIE
    <input type="submit">


</form>

movieproject/templates/details.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="550" height="400">
        </div>

        <div class="col-md-6">
            <h3>{{movie.name}}</h3>
            {{movie.desc}}<br>
            year - {{movie.year}}
            <br>
            <a class="btn btn-warning"  href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger"  href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
    {{form.as_p}}
<input type="submit">

    </form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movielist %}
        <div class="col-md-3">
            <div class="card" >
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" >
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>

    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Book now</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div> <br>

<center><a href="{% url 'movieapp:addmovie' %} " class="btn btn-success">Add Movie</a></center>

{% endblock %}